POST http://localhost:4004/odata/v2/portal/loginCheck
Content-Type: application/json

{
  "email": "alice.johnson@company.com"
}

### Resend OTP
POST http://localhost:4004/odata/v2/portal/loginCheck
Content-Type: application/json

{
  "email": "alice.johnson@company.com",
  "action": "resend"
}
### Verify OTP 
POST http://localhost:4004/odata/v2/portal/loginCheck
Content-Type: application/json

{
  "email": "alice.johnson@company.com",
  "otp": "433978"
}